#!/usr/bin/env bash
# Diplay numbers from 1 to 100:
# If number is a multiple of 3 and 5 - "FizzBuzz"
# If number is a multiple of 3 - "Fizz"
# If number is a multiple of 5 - "Buzz"
i=1

while [ $i -le 100 ]
do
	if [ $((i % 3)) -eq 0] && [$((i % 5)) != 0 ]
	then
		echo "Fizz"
	elif [ $((i % 3)) != 0] && [$((i % 5)) -eq 0 ]
	then
		echo "Buzz"
	elif [ $((i % 3)) -eq 0] && [$((i % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	else
		echo "$i"
	fi
	i=$((i + 1))
done
