#!/usr/bin/env bash
# Tells a story based on the contents of the `/etc/passwd` file.

IFS=$'\n'
for line in $(cat "/etc/passwd"); do
  IFS=':' read -r username password uid gid info home shell <<< "$line"
  echo "The user $username is part of the $gid gang,"\
  "lives in $home and rides $shell."\
  "$uid's place is protected by the passcode $password,"\
  "more info about the user here: $info"
done
