#!/usr/bin/env bash
# Displaying "Best School" 10 times
# 9th element display "Best School" and then "Hi"
i=0
while [ $i -lt 10 ]
do
    echo "Best School"
    if [ $i -eq 8 ]
    then
        echo "Hi"
    fi
    i=$((i + 1))
done
