#!/usr/bin/env bash
# loop from 1 to 10 and:
# display "bad luck" for the 4th element
# display "good luck" for the 8th element
# display "Best School" for the other elements
i=0
while [ $i -lt 10 ]
do
    if [ $i -eq 3 ]
    then
        echo "bad luck"
    elif [ $i -eq 7 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    i=$((i + 1))
done
