#!/usr/bin/env bash
# Displaying "Best School" 10 times
# 4th element display "bad luck"
# 8th element display "good luck"
i=0
while [ $i -lt 10 ]
do
    if [ $i = 4 ]
	then
		echo "bad luck"
	elif [ $i = 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
    i=$((i + 1))
done
