#!/usr/bin/env bash
# loop from 1 to 20 and:
# display "bad luck from China" for the 4th element
# display "bad luck from Japan" for the 9th element
# display "bad luck from Italy" for the 17th element
# display number for the other elements
i=1
while [ $i -le 20 ]
do
    case $i in
        4)
            echo "$i"
            echo "bad luck from China"
            ;;
        9)
            echo "$i"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$i"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$i"
            ;;
    esac
    i=$((i + 1))
done
