#!/usr/bin/env bash
# loop from 1 to 20 and:
# display "bad luck from China" for the 4th element
# display "bad luck from Japan" for the 9th element
# display "bad luck from Italy" for the 17th element
# display number for the other elements
i=1
while [ $i -lt 21 ]
do
    if [ $i -eq 3 ]
    then
        echo "bad luck from China"
    elif [ $i -eq 8 ]
    then
        echo "bad luck from Japan"
    elif [ $i -eq 16 ]
    then
        echo "bad luck from Italy"
    else
        echo "$i"
    fi
    i=$((i + 1))
done
