#!/usr/bin/env bash
# Display the time for 12 hours and 59 minutes
# display hours from 0 to 12
# display minutes from 1 to 59
i=0
while [ $i -le 12 ]
do
    echo "Hour: $i"

    j=0
    while [ $j -le 58 ]
    do
        j=$((j + 1))
        echo "$j"
    done
    i=$((i + 1))
done
