#!/usr/bin/env bash
# loop from 1 to 20 and:
# display "bad luck from China" for the 4th element
# display "bad luck from Japan" for the 9th element
# display "bad luck from Italy" for the 17th element
# display number for the other elements
i=0
while [ $i -le 12 ]
do
    echo "Hour: $i"

    j = 0
    while [ $j -le 60 ]
    do
        j=$((j + 1))
        echo "$j"
    done
    i=$((i + 1))
done
